### ISSUE TITLE
Crash on CAN frame with unknown CANID

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#10]
I ran MMC-Server with a layout that has two CANMIO-Universal and a CANCMD and one CANCAB. 
If I start MMC-Server while a CANCAB has a loco assigned I get a crash with this stack trace.
```
mergAdminNode: NUMEV Opcode 74 processed
mergAdminNode: NUMEV Opcode 74 processed
mergAdminNode: DKEEP Opcode 23 processed
jsonServer: Data Received : ":SA780N2202;"
jsonServer: broadcast : ":SA780N2202;"
uncaughtException: encode: unable to determine message type - no ID_TYPE present
Error: encode: unable to determine message type - no ID_TYPE present
    at cbusLibrary.encode (D:\Sources\MMC-SERVER\node_modules\cbuslibrary\cbusLibrary.js:706:23)
    at broadcast (D:\Sources\MMC-SERVER\device_hub\jsonServer.js:72:35)
    at Socket.<anonymous> (D:\Sources\MMC-SERVER\device_hub\jsonServer.js:54:17)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

This does not occur if I start MMC-Server without any locomotives active in CANCAB.
I don't get any problems if I later assign a locomotive and run it.

If I capture messages with FCU and JMRI CBUS Console I don't see any messages with this CANID (A780) or the OPCODE 0x22. I would conclude that FCU and JMRI ignores CAN messages with invalid CANID.

There are two consequences here:
1. Ignore this message with (what I suspect is a) invalid CANID.
2. Error handling needs to be improved in general. I have seen other cases where errors are not handled well and quietly leaves the browser with a web page that doesn't do anything. This item might be a separate issue entry.

**Comment by SvenRosvall** [comment]
[debug.log](https://github.com/david284/MMC-SERVER/files/13811383/debug.log)

**Comment by david284** [comment]
A design change from a previous project was to use json instead of GridConnect encoding - some functions missed this change

mergAdminNode currently has the following function that returns a GrdiConnect encoded string

```
    QLOC(sessionId) {
        return cbusLib.encodeQLOC(sessionId);
    }

```

Whereas equivalent functions build & return a JSON string, e..g.

```
    NERD(nodeId) {//Request All Events
        let output = {}
        output['mnemonic'] = 'NERD'
        output['nodeNumber'] = nodeId
        return output
    }

```

**Comment by SvenRosvall** [comment]
Fixed in commit https://github.com/david284/MMC-SERVER/commit/b8419f9fcdd042bd90249b3f48539e35a83c7fd6
