### ISSUE TITLE
Support for multiple layouts

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#12]
On the settings screen it is possible to set the layout name. This suggests to me that there would be support for more than one layout.
I have need for support for multiple layouts. I have a few layouts and lab setups that I want to configure with the same PC. I want to separate out the data for each layout so that events don't collide across layouts.

Compare this with the set of configurations that FCU uses.

Probably requires a major rework as the persisted data needs to reorganised in selectable files.

**Comment by david284** [comment]
Currently, the data persisted with 'layout' is

1. layout name 'title'
2. subtitle
3. Starting node number to be allocated when a new node number requested (will allocate next available after this number)
4. Nodes - with name, colour & group (defaults are created for all nodes seen)
5. Events - with name, colour & group (only created when event edited)

You can't currently change layout - obviously that needs adding
I would have thought ability to change to an existing layout or create new would be sufficient?
Is the list of items above sufficient as a starting point?

**Comment by SvenRosvall** [comment]
> Is the list of items above sufficient as a starting point?
Yes, very good list.
