### ISSUE TITLE
Event group and colour not shown in Node Stored Event page

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#14]
Events can be assigned a group and a colour in the Events page. 
However this group and colour is not shown in the list of stored events for a node. There is no column for the group. 

It would be nice to have the colour show up also in the stored events list. Group is not so critical.

It would also be nice to be able to assign group and colour in the stored events page. (We can name the events there now.)

**Comment by david284** [comment]
Groups added - declining to add colors at this point
