### ISSUE TITLE
Event colours and groups are not persisted

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#15]
Repro steps:
1. I set colour and group for a few events in the events page. 
2. Stop and start MMC-Server
3. The events show up with default black colour and no group.

**Comment by david284** [comment]
You can view the values that are persisted in the JSON ->settings tab
The values do appear to be written to the file layoutDetails.json, as they appear in the setting tab after startup
But on startup, the values don't appear to be used to render the page, so I believe it's a startup / render issue, not a persistence issue

**Comment by SvenRosvall** [comment]
Makes sense about startup. I did see the colors coming up later.

**Comment by SvenRosvall** [comment]
Seems to work fine now after work on #12 .
