### ISSUE TITLE
Sorting events list

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#18]
I cannot sort the events by clicking on the header.
I can sort events in the Node->Stored Events panel.

**Comment by david284** [comment]
Yes, I turned off sorting in the events page
Reason is, the drop down 'details' is created at the point the initial page is rendered, and if the table order is changed, the drop down details don't get updated, so you're then editing the wrong event
I don't see an easy way to fix that, apart from a major rework of the page, so disabled sorting to ensure what is there does work reliably
You'll notice there are no arrows on the column headings, which you would get if sortable
I won't close this issue, but leave as an emhancement

**Comment by david284** [comment]
Events list is now sorted by 'event identifier' (event node number/event number pair)

I think this is best if we intend to allow filtering by 'group' at a later date
