### ISSUE TITLE
Use module name for modules without descriptor file

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#2]
This is a nice to have for Arduino developers who create new modules.

An unknown module comes up with just an identifier number in the node list. It would be nice to see the module type name as returned by RQMN. (Note that the module must be in Learn mod or Setup mode.)

**Comment by david284** [comment]
In CBUS modules, I understand NAME is only available in setup mode - and I believe going into setup will result in the node releasing it's node number?
Maybe one to discuss at the next meeting

**Comment by SvenRosvall** [comment]
Oh, I was only looking at the VLCB spec. Yes I see now that CBUS only does this in setup mode. And yes it is most useful when adding a new node. FCU keeps it cached from then on.

Comparing with the "recreate" feature in FCU. It does not retrieve names for modules. Also it doesn't accept my Arduino module as it doesn't recognize the module type and/or the Service Descriptor flag.

Closing this.
