### ISSUE TITLE
If module name doesn't exist

### ISSUE THREAD

**Issue by david284** [david284/MMC-SERVER#21]
If module name doesn't exist, automatically retrieve it by requesting NAME from module
And then create an entry in a 'user' mergConfig file (so it's not lost on an update)
The lookup for module name would search the user version first, then the 'production' version

Consideration needs to be applied to only doing one module at a time, as they need to be in learn mode to read NAME, and there can only be one mode in learn mode at any time
Maybe it needs a simple queuing 'fifo' system?

**Comment by david284** [comment]
For VLCB modules, there is no need to put the module into learn mode, so could be done as a 'normal' request, no conflict with any other module - just need to check the VLCB flag in the flags parameter field
So no need for any 'queuing' for VLCB modules

**Comment by SvenRosvall** [comment]
RQMN requires the module to be in Learn or Setup mode. 
Note that for CBUS modules they need to be in Setup mode for RQMN.

**Comment by david284** [comment]
Thanks for that - I mixed up setup & learn
So, using NAME response isn't a workable solution for CBUS modules - can't guarantee they've been setup on this system, and can't programmatically put them into setup - so can't guarantee we will have the NAME response 
Whilst it could be done for VLCB, will still need to avoid conflict if they have to be in 'learn'
Needs a bit more thought....

**Comment by david284** [comment]
Sever now looks for a 'registered' name - if that doesn't exist, it looks for a module definition file with a matching module identifier (manufacturer & id) - in first the user module directory  & then the system module directory and uses the name segment from the first filename found that matches the module identifier (ignores the version number segment)
Only if non of these return a result will it set module name to 'Unknown'
The client application has been changed to allow the upload of any file name, to facilitate the loading of a module descriptor file of the right name to resolve any 'Unknown' module issues
