### ISSUE TITLE
Show un-setup modules in node list

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#24]
It would be nice to show nodes that are not yet set up. I.e. CBUS SLiM mode nodes and VLCB nodes in Uninitialized mode. 
It would be nice to see all nodes connected on the LCB. 

I am not sure if this is even possible and what information to show in the node list as MMC cannot query the nodes.

**Comment by david284** [comment]
I believe the only way to 'find' modules is by the 'broadcast' QNN command - which should invoke a PNN response from every node
If the module hasn't been allocated a node number (i.e. un-setup), then  I don't believe it will respond, so can't be detected

Producers setup in 'SLIM' mode I believe do have node numbers, so should respond - so will show up
I believe SLIM 'consumers' may not have node numbers, so I don't believe they would respond to QNN in that case

As I'm unaware of any other mechanism to detect modules, then I will close this issue
