### ISSUE TITLE
Cannot teach a new event to universal

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#28]
Press ADD EVENT for a node. A dialogue comes up where I can select Short Event and then a Device Number. The new event does not show up, even after pressing REFRESH or restarting MMC.

This is strange as the messages look correct. Here is a dump:
Out: NNLRN (53) Node 102
Out: EVLRN (D2) nodeNumber 0 eventNumber 35 Event Variable Index 1 Event Variable Value 0
Out: NNULN (54) Node 102
Out: NNULN (54) Node 102
In: WRACK (59) Node 102
Out: RQEVN (58) Node 102
Out: NERD (57) Node 102
In: NUMEV (74) Node 102 Event Count 19

The node had 19 events before adding event 35. Expected the NUMEV response to increase.

Comparing with FCU. It sets the node in NNLRN and then sends one EVLRN for each EV (20 of them) in that event. And then a single NNULN.

I wonder if there is a race condition here where MMC sends a NNULN before the WRACK has come back?

This was tested on a CANMIO (Universal).

**Comment by SvenRosvall** [comment]
A workaround is to create the short event in FCU. Once created MMC can configure the EVs.

**Comment by spikyian** [comment]
Universal treats a EV value of 0 to be 'nothing' so writing an EV value 0 is actually a way of deleting entries.

**Comment by dpharris** [comment]
Could the MDF for the CANMIO-Uni specify a non-zero default value for EV1?  Then the event would be created, and the user can edit it.  
Could Universal  have a 'null' option for produced event actions?

**Comment by david284** [comment]
_Universal treats a EV value of 0 to be 'nothing' so writing an EV value 0 is actually a way of deleting entries._

When you say 'entries' - do you mean deleting whole events or just 'event variables' in your dynamic tables?
I don't recall this being a problem before - I believe Nigel's code has always created events by using ev1 with a value of 0

**Comment by spikyian** [comment]
I mean deleting an Action. There is the NNULN opcode for deleting an event in its entirety but nothing for deleting an EV, only create/modify so I chose to modify to 'Nothing'. I really wanted to be able to remove and shift the EVs down and also insert but that would be too tailered for Happenig/Actions use of EVs.

**Comment by spikyian** [comment]
I mean EVs (whole events can be deleted using EVULN).
When the EVs represent a sequence of Actions it would be nice to insert and remove Actions but there are no opcodes for that and the only opcodes aloow for create/modify so to delete I overwrite with the value zero.

Creating an event with just EV1=0 will be ignored by Universal.

**Comment by dpharris** [comment]
Can we not assign an unused value of EV#1, say 0xFF, as a NULL-producer?
Then MMC can teach a new event with: EVLRN(event,1,0xFF).
The user can edit it to whatever they like.

Perhaps I am not understanding, as
https://merg.org.uk/merg_wiki/doku.php?id=cbus:canmio_fw3 lists EV#1==0 as "No
Happening is mapped to the event.", which seems to be a legitimate value,
no?

David

**Comment by david284** [comment]
This appears to be specific to adding any event (long or short) to universal when EV1=0
Other modules tried (CANACC5 & CANACE8C) work ok
I've changed the name to reflect that

**Comment by SvenRosvall** [comment]
Ian wrote:
> Creating an event with just EV1=0 will be ignored by Universal.

OK, that is the problem we are having. And this is where I think the Teaching service doc need to be tightened up as it allows for this interpretation.

I don't like magic numbers as David H. suggests. The value 255 has a meaning to CANPAN for example.

As David E. says, we are where we are and it might be easier to fix MMC somehow. FCU is fine with this.
MMC could open the dialogue for edititing variables for the newly created event (as FCU does). This means that (hopefully) at least one EV will be non-zero.

I have asked David E. for an enhancement to open the editing EVs dialogue when an event from another node is taught. This is to reduce some clicks and reduce the risk that the wrong node is chosen from the list of nodes that this event is taught to. This enhancement will solve the teach problem for CANMIO.

**Comment by dpharris** [comment]
Why doesn't the window for adding/editing an event include the event-number
and the EVs, rather than having two windows?

**Comment by dpharris** [comment]
Aside: The 'magic number' is suggested to be a default value supplied in
the MDF for the Universal. If no default-value is supplied, then 0 (zero)
would be used.

**Comment by david284** [comment]
> Why doesn't the window for adding/editing an event include the event-number and the EVs, rather than having two windows?

The aim was to have a direct way to access the EVLRN command, to easily add any event (inc. spoofed), as an alternative to the 'teach' mechanism, which obviously can only add existing events to another module
(My opinion is the FCU seems to prevent some operations that ought to be possible with CBUS commands, without having to resort to 'debug' mode)
So exposed the 'node number/event number' pair as two windows (or just one for short events)
Obviously I made the incorrect assumption that I could use EV1=0 to narrow the operation to just creating the event

**Comment by spikyian** [comment]
I could allow VLCB Universal to store EVs with value 0 if required.

**Comment by david284** [comment]
_I could allow VLCB Universal to store EVs with value 0 if required._
I think if creating events with all EV's set to 0 isn't possible, then it needs to be recognised somewhere, as otherwise an EV value of 0 is presumed to be a valid value - and by implication, all the EV's being 0 is equally valid
However, we'll need to support existing code, so changing new code unfortunately won't resolve the stated issue

**Comment by SvenRosvall** [comment]
> I could allow VLCB Universal to store EVs with value 0 if required.

Ian, the problem is not the EV, but that the event itself is not created for a EVLRN with EV value 0. Could you create the event for EVLRN regardless of the value of the EV? 
Yes, it may sound daft to create an event without any EVs. But this would comply with the Teaching Service spec (according to my reading). This would solve the problem here.

As David says, we have to live with existing code. This is why I am arguing for a change to MMC to open up the Edit EV screen when a new event is taught/created.

**Comment by spikyian** [comment]
Yes that is what I mean by allowing the EV=0 these would then be stored in the given event. I would be quite a bt of work to retest as there could have many impacts within the event and Action processing loops.
