### ISSUE TITLE
Node button "Add Event" should be disabled for nodes without event services

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#32]
Minor issue. If I press the button I get an error popup with "This module does not support any stored events"
But it would be nice if the button was greyed out.
Same with the Variables button for nodes without NV Service or zero NVs. 

I am testing this with a version of the Arduino CANEMPTY example sketch where I took out all the services except MNS and CAN Service to produce the tiniest example I could. 

"Parameters" report zero NVs and zero events as expected.

**Comment by david284** [comment]
Yes, it would be nice - but it would require thenreading of those parameters for all nodes in the node list, as at startup I wouldn't know those values (and don't want to rely on stored values, as it might be different, like when changing layouts)
If their was a significant number of nodes that would take a noticeable time - before the list can be displayed
And if you had to read the services as well, that'd take even longer
'display only' items like number of events can be done by updating 'as and when' received, but anything that enables an action (like enabling a button)I believe would need to correct immediately

**Comment by SvenRosvall** [comment]
Thanks for explaining. I thought you already got the flags i parameter #8 to determine if each node is a VLCB node. Or do you use another mechanism for determining if the node is a VLCB node?

So, there is no need to read all parameters, just #8 which contains the flags.

This is probably low priority now as nodes without events will be quite rare. However when we get into DCC we might see more nodes without events. Although CANCMD does actually produce and consume events.

**Comment by david284** [comment]
yes, I do use the flags to check if it's vlcb or not (thats how I set the CBUS/VLCB column)
But I don't believe the flags tell me if it supports any stored events or zero NV's
And I'd have to interrogate further to find out if it has an NV service

**Comment by SvenRosvall** [comment]
Right. Param #8 has flags for event consumer (bit 0) and event producer (bit 1). If both are off then there won't be any events. This is OK for the "Add Events" button. This has nothing to do with NVs. (Sorry for mentioning them at the top.)

Max number of events is in param #4. Not sure if there is a risk that there would ever be a consistency between this and the producer/consumer flags. 

Anyways, this is a low prio, nice to have some time in far future.

Btw, Number of node variables is in param #6. Reading this param could control if the "Variables" button should be active. I don't think this is worth the effort as I expect most module types to have some node variables.

**Comment by david284** [comment]
Yep, but I believe that some legacy modules have default events, but no stored events - so you can't 'add events' - so they are producers but report 0 stored events - so just relying on

**Comment by SvenRosvall** [comment]
Ah, that is a good point about the producers with default only events.
