### ISSUE TITLE
Support for setting up a new node

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#4]
When I press the mode button to setup a new module, qfcu doesn't react to the RQNN.

It doesn't react to NNREL either. (for releasing a node number that the module had previously.)

**Comment by david284** [comment]
What are you expecting to happen when you press the mode button?

**Comment by SvenRosvall** [comment]
The mode button initates mode transition. See the Minimum Node Service spec: https://docs.google.com/document/d/1-5lRcENqJHMo-r0BPCVvRrQhwzuX3DKOoZPdjYohe5A/edit#heading=h.mdihfev6utj4

Pressing the mode button for 4 seconds makes the node enter Setup mode. If it is coming from Normal mode it will release the node number with NNREL. In setup mode it will ask for a new node number. (RQNN) At this point I expect QFCU to provide a new free node number, possibly via a dialogue box (which old FCU does). The old FCU also asks for node name and some parameters at this stage to provide some info for the user in this dialogue box.

**Comment by david284** [comment]
I know Nigel implemented this to automatically assign the node number without a pop-up when it gets an RQNN
I have seen this work, but not tried it recently
