### ISSUE TITLE
Show "linked nodes" for events

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#41]
In the Event View it would be nice to see how many nodes have been taught this event.

**Comment by david284** [comment]
I'm looking at showing how many nodes have the event as a stored event
Subtle difference is that for universal, it may not be a taught event, but a default event
Although I don't think the distinction matters - it's still a node that has that event
________________________________
From: Sven Rosvall ***@***.***>
Sent: 19 October 2024 18:13
To: david284/MMC-SERVER ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [david284/MMC-SERVER] Show "linked nodes" for events (Issue #41)


In the Event View it would be nice to see how many nodes have been taught this event.

**Comment by david284** [comment]
completed
