### ISSUE TITLE
Delete event from Events View

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#42]
Some events may show up in the Events View eventhough they are not taught to any nodes. This may happen when an event is added directly or an event has been deleted from all nodes. It would be nice to be able to delete such unused, unwanted events.

It will be tricky to delete events that do exist on one or more of the nodes. One option is to delete this event from any nodes. FCU does it this way. This option can be dangerous. A better option is to only allow deleting events that do not exist in any nodes.

Both options above require knowledge about what nodes have been taught this event. 

There is a plan to add a feature to show "linked nodes" i.e. nodes that know about this events. See #41 Reconsider this issue when "linked nodes" has been implemented.

**Comment by david284** [comment]
Agree with pretty much all you've said

I'll have to have a look at tracking events in nodes again



________________________________
From: Sven Rosvall ***@***.***>
Sent: 19 October 2024 18:14
To: david284/MMC-SERVER ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [david284/MMC-SERVER] Delete event from Events View (Issue #42)


Some events may show up in the Events View eventhough they are not taught to any nodes. This may happen when an event is added directly or an event has been deleted from all nodes. It would be nice to be able to delete such unused, unwanted events.

It will be tricky to delete events that do exist on one or more of the nodes. One option is to delete this event from any nodes. FCU does it this way. This option can be dangerous. A better option is to only allow deleting events that do not exist in any nodes.

Both options above require knowledge about what nodes have been taught this event.

There is a plan to add a feature to show "linked nodes" i.e. nodes that know about this events. See #41<https://github.com/david284/MMC-SERVER/issues/41> Reconsider this issue when "linked nodes" has been implemented.

**Comment by david284** [comment]
completed
