### ISSUE TITLE
Bug: Add Event with same NN/EN as existing event overwrites/deletes old event.

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#44]
1. My CANMIO has default events for input channels. I.e. the produced events for the input channel.
2. I add a new event in the Node event view, a long event with the same NN and EN as one of the default events for an input channel. 
    MMC happily opens up the Edit Event Variables dialogue without checking that the event already exists. 
    The Edit Event Variables dialogue is filled with values zero all over. I.e. it is not reading the existing event.
3. I don't edit anything. Leaving all EVs to zero. Close the edit EV dialogue.
    As all EVs are now zero, Universal deletes that event.
4. Refresh the events for this node and the event is indeed gone.

Main bug here is that there is no check for existing event. If you decide that it is allowed to add an event that already exist then I expect MMC to treat this as "Edit Event Variables" and load the existing value.

**Comment by david284** [comment]
closed with
bc47f77fcfbf0f1322ebb9e6466088c786c22b70
