### ISSUE TITLE
Send events from Stored Events page

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#5]
It would be nice to be able to send events from the event list in the Node -> Stored Events page.
Arguments:
1. Be able to test newly created events without having to switch over to the Events page.
2. Consumed events don't show up in the Events page until they have been triggered somehow.

**Comment by david284** [comment]
I get that, but one question - should you only be able to do that from 'producer nodes'? - that would seem to make logical sense

**Comment by SvenRosvall** [comment]
No, I want to do that for any type of node, especially consumer nodes as there is no other way to trigger those events until they have been produced somewhere else and now available in the Events page. 
I also want to do this for consumed events as I use this to test that my settings (EVs) are correct for that event on that node. I don't want to switch to the Event page and then discover that I need to make more adjustments to that event.

**Comment by SvenRosvall** [comment]
New layout allows testing events on and on closer to where the events are edited.
