### ISSUE TITLE
Progress indicator when retrieving lots of information

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#7]
There are a few situations where retrieving information for a page is taking lots of time. 
One example is the page for showing node variables for a node that has a lot of node variables. CANCMD has 144 node variables. 
If I monitor the CBUS messages in FCU I see that there are NVANS messages arriving long after the Variables page is shown.
It would be nice to know that QFCU is still updating the info on the page that is shown.

**Comment by SvenRosvall** [comment]
CANCMD was just an example. I think CANMIO-Universal and CANGATE also has a large number of node variables.

**Comment by david284** [comment]
Yep - I guess I should remove all the types that aren't fully supported
It's a bit difficult, as I only have 3 'true' CBUS modules, so even the one's I think are fully supported (probably about 6) I'm only going by referencing the documents I've managed to find
Maybe we need a process to validate support for each module?

**Comment by SvenRosvall** [comment]
No, please don't remove types that are not 100% correct and supported. MMC would be very limited if you did. Instead open up for bug reports and fix them when differences are discovered.

**Comment by david284** [comment]
Added 'traffic' window in the left hand side bar, that shows the last 5 messages - this does show when the bus is busy
Not sure if this is sufficent, so won't close the issue, but an initial attempt to provide an indication

**Comment by SvenRosvall** [comment]
Yes, happy to close this issue. The traffic window is enough at this stage in development. 
If others think there should be another way to show that MMC is still reading info, then open a new issue with a better description of what is needed.
